### ISSUE TITLE
 Clear form data after submission

### ISSUE THREAD

**Issue by rafaelarc** [jamiewilson/form-to-google-sheets#11]
Hello everyone, I'm new to programming and I'm using this method to send a simple subscription to my static website. I would like to ask for help to adapt this code to clear the fields of the form shortly after sending the data, I tried some methods with jquery and have erased the data before sending.

```
<script>
  const scriptURL = 'macro-here'
  const form = document.forms['google']

  form.addEventListener('submit', e => {
    e.preventDefault()
    fetch(scriptURL, { method: 'POST', body: new FormData(form)})
      .then(response => console.log('Success!', response))
      .catch(error => console.error('Error!', error.message))
  })
</script>
```

**Comment by picocodes** [comment]
Did you try clearing then form fields inside your `.then` callback?

**Comment by picocodes** [comment]
```



    form.fireEvent("reset");


```

>
>
>

**Comment by flinbu** [comment]
`form.reset()` works fine inside `.then` callback
