### ISSUE TITLE
CORS and CORB policy error

### ISSUE THREAD

**Issue by GenericNerd** [jamiewilson/form-to-google-sheets#26]
Even on the demo, local or published webpages, there is always a CORS and CORB policy error
https://i.imgur.com/JMH71EK.png

**Comment by particthistle** [comment]
I just had a CORS error on another project, and to get around it I followed https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin and added a line to .htaccess to specify the origin-list. It a wildcard on the short url tool I was configuring, but you might need to add something specific.

Where https://chromestatus.com/feature/5629709824032768 goes into why you're seeing the alert, https://www.chromium.org/Home/chromium-security/corb-for-developers might shed more info, and that may include Content-Type and X-Content-Type-Options" response headers.

Hope that's a starting point.

**Comment by ankur-sardar** [comment]
@particthistle How did you add the ` Access-Control-Allow-Origin: *` in your script?

**Comment by particthistle** [comment]
@ankur-sardar you just need to add the following line to your .htaccess file:

`Header set Access-Control-Allow-Origin '*'`

**Comment by akinhwan** [comment]
is this still necessary? .htaccess file? where is this file normally

**Comment by particthistle** [comment]
@akinhwan,

I know that the solution fixed the issue for YOURLS.

Setting the PHP Header using .htaccess is a common solution. The .htaccess file will be in the root of your site (eg /public_html/ folder) to impact sitewide, or in a different folder to impact just that folder.

I don't know if @GenericNerd closed it as it resolved it for them?

**Comment by GenericNerd** [comment]
@particthistle I should have commented really, sorry about that. It seems that it fixed the issue for me.

**Comment by jpmayorga** [comment]
The issue is not fixed! Where i must modify Header set Access-Control-Allow-Origin '*'

**Comment by baumant** [comment]
Make sure you allow access to "Anyone" when deploying the script, if you set it to "only myself" it will give CORS errors.
<img width="560" alt="Screen Shot 2021-04-20 at 3 58 38 PM" src="https://user-images.githubusercontent.com/8883043/115473832-4747a500-a1f1-11eb-8d07-0911006af9a7.png">

**Comment by GenericNerd** [comment]
@baumant I'm not quite sure where this is from, but that is certainly not a raw programming interface.

@jpmayorga As @particthistle had commented on previously, you need to place the .htaccess with `Access-Control-Allow-Origin: *` in the root of the directory.
