### ISSUE TITLE
this is why data dont show on your sheet

### ISSUE THREAD

**Issue by n4j1Br4ch1D** [jamiewilson/form-to-google-sheets#42]

**Comment by Skeamy876** [comment]
what do you mean by that?

**Comment by ad11monsieur** [comment]
> // return e.parameter[header].replace(/=/g, '')

you mean in the "code.gs"?

**Comment by Shamanovski** [comment]
yes, he means in the code.gs. Anyway, It didn’t help me to solve the problem with updating google sheet

**Comment by gauravkeerthi** [comment]
This is cryptic. @n4j1Br4ch1D 
Normally if you offer a response on multiple comments, it's good practice to let people know which file you are referring to, which line this is, (copying out the code and showing the change in context is best).
