### ISSUE TITLE
Adding date and time to the sheet when the form is submitted

### ISSUE THREAD

**Issue by SakshhamTheCoder** [jamiewilson/form-to-google-sheets#46]
Any ideas how can i add a function in which when someone submits the form, the date and time of the submission is sent to spreadsheet?

EDIT- I have used some google scripts available online which add a timestamp in a cell if a particular cell is modified, but they doens't seem to work. I think the data which gets added in the spreadsheet on submitting the form is not added by a user which overrides the active cell function in the script, so it doesn't work. I may be wrong here but anyways please help me with this

**Comment by rocksvicks** [comment]
Ok its very simple.
1) Go to selection  Google Sheet 
2) selete ROW for timestamp (ex 1st rowA:A for timestamp)
3) Menu bar Format>Number>Date Time
4) Done 
thanks
sorry very late replay
