### ISSUE TITLE
Data not showing when form is filed from any other location

### ISSUE THREAD

**Issue by SakshhamTheCoder** [jamiewilson/form-to-google-sheets#47]
Another issue i'm facing is that whenever I fill the form from my home network, the data gets saved in the sheet. But whenever my friend fills the same form from his home, the form doesn't get saved in the sheet. I have asked my friend to fill that form from his house(1km from my house) and my brother from his house(different country). Data didn't get saved :(
Any help is highly appreciated

**Comment by rocksvicks** [comment]
@SakshhamTheCoder Delete and try again..
watch step by step
